"""Phase 6: Financial Health & Growth Report Service.

Collects real user financial data, computes health indicators,
and generates a structured, professional multi-page PDF report using fpdf2.

CRITICAL ARCHITECTURAL CONSTRAINTS:
1. No fabricated data. Missing fields must display as 'Not available'.
2. PDF generated via fpdf2 with valid %PDF header.
3. Strict user isolation: users can only purchase, generate, and view their own reports.
4. Demo purchases and revenue events must be clearly tagged isDemo=True.
5. Standard FPDF core fonts use 'Rs.' or 'INR' to guarantee 100% encoding safety.
"""

import base64
import json
from datetime import datetime, timezone
from typing import Dict, Any, Optional, List
from fpdf import FPDF

from app.database import get_collection
from app.models.base import generate_id, utc_now
from app.services.tax_service import TaxInput, calculate_tax, DEFAULT_TAX_YEAR


class PennoraPDF(FPDF):
    """Custom FPDF layout with Pennora header, footer, and branding."""

    def header(self):
        self.set_fill_color(15, 23, 42)  # Dark slate navy
        self.rect(0, 0, 210, 16, "F")
        self.set_xy(10, 5)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(255, 255, 255)
        self.cell(120, 6, "PENNORA  |  FINANCIAL HEALTH & GROWTH REPORT", 0, 0, "L")
        self.set_font("Helvetica", "I", 8)
        self.cell(70, 6, "CONFIDENTIAL & PROPRIETARY", 0, 1, "R")
        self.set_y(22)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(148, 163, 184)  # Slate light
        self.cell(
            0,
            5,
            f"Page {self.page_no()} of {{nb}}  |  Generated by Pennora Intelligence  |  Educational Planning Tool - Not SEBI/Tax Advisory",
            0,
            0,
            "C",
        )


def collect_report_data(user_id: str) -> Dict[str, Any]:
    """Collects real user profile, goals, transactions, and tax calculations.

    Missing fields are explicitly kept as None to prevent fabrication.
    """
    users_coll = get_collection("users")
    user = users_coll.find_one({"_id": str(user_id)}) or {}

    profiles_coll = get_collection("financial_profiles")
    profile = profiles_coll.find_one({"userId": str(user_id)}) or {}

    goals_coll = get_collection("goals")
    raw_goals = goals_coll.find({"userId": str(user_id)}) or []
    goals_list = []
    total_target = 0.0
    total_saved = 0.0
    for g in raw_goals:
        target = float(g.get("targetAmount", 0.0) or 0.0)
        current = float(g.get("currentAmount", 0.0) or 0.0)
        total_target += target
        total_saved += current
        pct = round((current / target * 100), 1) if target > 0 else 0.0
        goals_list.append({
            "title": g.get("title", g.get("name", "Goal")),
            "targetAmount": target,
            "currentAmount": current,
            "progressPercent": pct,
            "category": g.get("category", "General"),
        })

    # Financial Profile Metrics (strictly real data)
    monthly_income = profile.get("monthlyIncome")
    monthly_income = float(monthly_income) if monthly_income is not None else None

    monthly_expenses = profile.get("monthlyExpenses")
    monthly_expenses = float(monthly_expenses) if monthly_expenses is not None else None

    savings_rate = None
    if monthly_income and monthly_income > 0 and monthly_expenses is not None:
        savings = monthly_income - monthly_expenses
        savings_rate = round((savings / monthly_income * 100), 1)

    # Health score composite (heuristic based solely on available real data)
    health_score = None
    if monthly_income is not None:
        score = 50.0
        if savings_rate is not None:
            if savings_rate >= 30:
                score += 25.0
            elif savings_rate >= 15:
                score += 15.0
            elif savings_rate > 0:
                score += 5.0
        if goals_list:
            score += 15.0
        health_score = int(min(100.0, max(0.0, score)))

    # Deterministic Tax Summary
    annual_income = (monthly_income * 12.0) if monthly_income is not None else 0.0
    t_input = TaxInput(gross_salary=annual_income, financial_year=DEFAULT_TAX_YEAR)
    tax_result = calculate_tax(t_input)

    return {
        "userId": str(user_id),
        "fullName": user.get("fullName", user.get("name", "Pennora Member")),
        "email": user.get("email", "Not available"),
        "monthlyIncome": monthly_income,
        "monthlyExpenses": monthly_expenses,
        "savingsRate": savings_rate,
        "healthScore": health_score,
        "goals": goals_list,
        "totalGoalsTarget": total_target if goals_list else None,
        "totalGoalsSaved": total_saved if goals_list else None,
        "taxResult": tax_result,
        "asOfDate": datetime.now(timezone.utc).strftime("%d %B %Y"),
    }


def generate_pdf_report(data: Dict[str, Any]) -> bytes:
    """Generates a professional 3-page PDF document using fpdf2.

    Returns the raw PDF bytes starting with %PDF.
    """
    pdf = PennoraPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(left=10, top=18, right=10)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=18)

    # ================= PAGE 1: EXECUTIVE SUMMARY & HEALTH SCORE =================
    pdf.add_page()

    # Title & User Block
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 8, "Comprehensive Financial Health & Growth Report", 0, 1, "L")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(190, 5, f"Prepared for: {data['fullName']} ({data['email']})  |  As of: {data['asOfDate']}", 0, 1, "L")
    pdf.ln(4)

    # Health Score Highlight Box
    box1_y = pdf.get_y()
    pdf.set_fill_color(241, 245, 249)
    pdf.rect(10, box1_y, 190, 24, "F")
    pdf.set_xy(15, box1_y + 3)

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(90, 6, "Overall Financial Health Score", 0, 0, "L")

    pdf.set_font("Helvetica", "B", 16)
    if data["healthScore"] is not None:
        if data["healthScore"] >= 70:
            pdf.set_text_color(16, 185, 129)
        else:
            pdf.set_text_color(245, 158, 11)
        pdf.cell(90, 6, f"{data['healthScore']} / 100", 0, 1, "R")
    else:
        pdf.set_text_color(100, 116, 139)
        pdf.cell(90, 6, "Not available", 0, 1, "R")

    pdf.set_xy(15, box1_y + 11)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(180, 5, "Quantitative benchmark based on savings capacity, cashflow surplus, and goal orientation.", 0, 1, "L")
    pdf.set_y(box1_y + 28)

    # Cashflow & Savings Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 7, "1. Cashflow & Savings Analysis", 0, 1, "L")

    # Table Header
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(95, 6, "Metric", 1, 0, "L", fill=True)
    pdf.cell(95, 6, "Value", 1, 1, "R", fill=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.cell(95, 6, "Monthly Inflow / Income", 1, 0, "L")
    val_inc = f"Rs. {data['monthlyIncome']:,.2f}" if data["monthlyIncome"] is not None else "Not available"
    pdf.cell(95, 6, val_inc, 1, 1, "R")

    pdf.cell(95, 6, "Monthly Outflow / Expenses", 1, 0, "L")
    val_exp = f"Rs. {data['monthlyExpenses']:,.2f}" if data["monthlyExpenses"] is not None else "Not available"
    pdf.cell(95, 6, val_exp, 1, 1, "R")

    pdf.cell(95, 6, "Calculated Savings Rate", 1, 0, "L")
    val_sr = f"{data['savingsRate']}%" if data["savingsRate"] is not None else "Not available"
    pdf.cell(95, 6, val_sr, 1, 1, "R")

    pdf.cell(95, 6, "Annual Projected Gross Income", 1, 0, "L")
    val_ann = f"Rs. {(data['monthlyIncome'] * 12):,.2f}" if data["monthlyIncome"] is not None else "Not available"
    pdf.cell(95, 6, val_ann, 1, 1, "R")

    pdf.ln(5)

    # Key Observations
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(190, 6, "Key Observations:", 0, 1, "L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(10)
    if data["savingsRate"] is not None:
        if data["savingsRate"] >= 20:
            pdf.multi_cell(190, 5, "- Healthy savings rate above the recommended 20% standard threshold.", new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.multi_cell(190, 5, "- Savings rate is below the optimal 20% benchmark. Review discretionary spending.", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.multi_cell(190, 5, "- Profile data is incomplete. Set up monthly income and expenses to unlock detailed cashflow insights.", new_x="LMARGIN", new_y="NEXT")

    # ================= PAGE 2: FINANCIAL GOALS & TARGETS =================
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 8, "2. Financial Goals & Capital Accumulation", 0, 1, "L")
    pdf.ln(2)

    goals = data.get("goals", [])
    if goals:
        pdf.set_fill_color(226, 232, 240)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(60, 6, "Goal Name", 1, 0, "L", fill=True)
        pdf.cell(35, 6, "Category", 1, 0, "L", fill=True)
        pdf.cell(45, 6, "Target (Rs.)", 1, 0, "R", fill=True)
        pdf.cell(50, 6, "Progress (%)", 1, 1, "R", fill=True)

        pdf.set_font("Helvetica", "", 9)
        for g in goals:
            pdf.cell(60, 6, str(g["title"])[:30], 1, 0, "L")
            pdf.cell(35, 6, str(g["category"])[:18], 1, 0, "L")
            pdf.cell(45, 6, f"{g['targetAmount']:,.2f}", 1, 0, "R")
            pdf.cell(50, 6, f"{g['progressPercent']}% (Rs. {g['currentAmount']:,.0f})", 1, 1, "R")

        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(95, 6, f"Total Target Capital: Rs. {data['totalGoalsTarget']:,.2f}", 0, 0, "L")
        pdf.cell(95, 6, f"Total Saved Capital: Rs. {data['totalGoalsSaved']:,.2f}", 0, 1, "R")
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(190, 8, "No active financial goals recorded. Goals can be created via Pennora Goals section.", 0, 1, "L")

    pdf.ln(8)

    # Net Worth & Investments Overview
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 7, "3. Investment Portfolio & Asset Allocation", 0, 1, "L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.set_x(10)
    pdf.multi_cell(
        190,
        5,
        "Portfolio asset allocations are synchronized from linked accounts and manual records. "
        "Diversification across equity index funds, fixed income (EPF/PPF), and liquid emergency funds "
        "is essential for risk-adjusted growth.",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    # ================= PAGE 3: TAX PLANNING & ACTION PLAN =================
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 8, "4. Deterministic Income Tax Planning (FY 2024-25)", 0, 1, "L")
    pdf.ln(2)

    tr = data["taxResult"]
    old_r = tr.old_regime
    new_r = tr.new_regime

    # Tax Comparison Table
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(70, 6, "Tax Component", 1, 0, "L", fill=True)
    pdf.cell(60, 6, "Old Regime (Rs.)", 1, 0, "R", fill=True)
    pdf.cell(60, 6, "New Regime (Rs.)", 1, 1, "R", fill=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.cell(70, 6, "Gross Salary / Income", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.gross_income:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.gross_income:,.2f}", 1, 1, "R")

    pdf.cell(70, 6, "Standard Deduction", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.standard_deduction:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.standard_deduction:,.2f}", 1, 1, "R")

    pdf.cell(70, 6, "Itemized Deductions (80C/80D/HRA)", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.chapter_via_deductions:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.chapter_via_deductions:,.2f} (N/A)", 1, 1, "R")

    pdf.cell(70, 6, "Net Taxable Income", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.taxable_income:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.taxable_income:,.2f}", 1, 1, "R")

    pdf.cell(70, 6, "Tax Before Rebate", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.base_tax:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.base_tax:,.2f}", 1, 1, "R")

    pdf.cell(70, 6, "Section 87A Rebate", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.rebate_87a:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.rebate_87a:,.2f}", 1, 1, "R")

    pdf.cell(70, 6, "Health & Education Cess (4%)", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.cess:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.cess:,.2f}", 1, 1, "R")

    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(70, 6, "Total Tax Liability", 1, 0, "L")
    pdf.cell(60, 6, f"{old_r.total_tax:,.2f}", 1, 0, "R")
    pdf.cell(60, 6, f"{new_r.total_tax:,.2f}", 1, 1, "R")

    pdf.ln(5)

    # Recommendation Callout
    box2_y = pdf.get_y()
    pdf.set_fill_color(240, 253, 244)  # Light emerald green
    pdf.rect(10, box2_y, 190, 20, "F")
    pdf.set_xy(15, box2_y + 3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(22, 101, 52)
    pdf.cell(180, 5, f"Recommendation: {tr.recommended_regime.upper()} REGIME (Potential Savings: Rs. {tr.tax_savings:,.2f})", 0, 1, "L")
    pdf.set_xy(15, box2_y + 9)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(180, 5, tr.recommendation_summary[:120], 0, 1, "L")

    pdf.set_y(box2_y + 25)

    # Strategic Action Plan
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 7, "5. Strategic Next Steps & Wealth Recommendations", 0, 1, "L")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.set_x(10)
    pdf.multi_cell(190, 5, "1. Maintain an emergency fund equivalent to 6 months of living expenses in high-yield liquid funds.", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(190, 5, "2. Optimize tax outflow by filing under the regime with maximum net disposable income.", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(190, 5, "3. Automate systematic monthly investments (SIPs) to achieve capital accumulation goals consistently.", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # Regulatory Disclaimer
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(148, 163, 184)
    pdf.set_x(10)
    pdf.multi_cell(190, 4, tr.disclaimer, new_x="LMARGIN", new_y="NEXT")

    # Output bytes
    return bytes(pdf.output())


def purchase_report(user_id: str, is_demo: bool = True) -> Dict[str, Any]:
    """Records a report purchase, creating payment, revenue, and report entries."""
    users_coll = get_collection("users")
    user = users_coll.find_one({"_id": str(user_id)})
    if not user:
        raise ValueError(f"User {user_id} not found.")

    report_id = generate_id()
    payment_id = generate_id()
    amount = 499.0

    # 1. Create Payment record
    payments_coll = get_collection("payments")
    payment_doc = {
        "_id": payment_id,
        "userId": str(user_id),
        "amount": amount,
        "currency": "INR",
        "planCode": "financial_report_v1",
        "paymentMethod": "demo" if is_demo else "card",
        "status": "paid",
        "taxAmount": round(amount * 0.18, 2),
        "netAmount": round(amount * 0.82, 2),
        "isDemo": is_demo,
        "createdAt": utc_now(),
        "updatedAt": utc_now(),
    }
    payments_coll.insert_one(payment_doc)

    # 2. Record Revenue Event (separated demo vs real)
    rev_coll = get_collection("revenue_events")
    rev_doc = {
        "_id": generate_id(),
        "userId": str(user_id),
        "revenueSource": "PREMIUM_FEATURE",
        "eventType": "report_purchase",
        "amount": amount,
        "taxAmount": round(amount * 0.18, 2),
        "netRevenue": round(amount * 0.82, 2),
        "currency": "INR",
        "status": "COMPLETED",
        "isDemo": is_demo,
        "createdAt": utc_now(),
    }
    rev_coll.insert_one(rev_doc)

    # 3. Create Report record
    reports_coll = get_collection("financial_reports")
    report_doc = {
        "_id": report_id,
        "userId": str(user_id),
        "reportType": "financial_health_growth",
        "status": "pending",
        "pdfBytes": None,
        "purchaseId": payment_id,
        "isDemo": is_demo,
        "summaryJson": None,
        "generatedAt": None,
        "asOfDate": utc_now(),
        "createdAt": utc_now(),
        "updatedAt": utc_now(),
    }
    reports_coll.insert_one(report_doc)

    return report_doc


def generate_and_store_report(user_id: str, report_id: str) -> Dict[str, Any]:
    """Generates the PDF report for the user and stores base64 payload in the database."""
    reports_coll = get_collection("financial_reports")
    report = reports_coll.find_one({"_id": str(report_id)})
    if not report:
        raise ValueError(f"Report {report_id} not found.")

    if str(report["userId"]) != str(user_id):
        raise PermissionError("Access denied: You can only generate your own reports.")

    # Collect data & generate real PDF
    data = collect_report_data(user_id)
    pdf_bytes = generate_pdf_report(data)

    # Encode to base64
    b64_pdf = base64.b64encode(pdf_bytes).decode("ascii")

    summary = {
        "healthScore": data["healthScore"],
        "monthlyIncome": data["monthlyIncome"],
        "savingsRate": data["savingsRate"],
        "recommendedRegime": data["taxResult"].recommended_regime,
        "taxSavings": data["taxResult"].tax_savings,
    }

    now = utc_now()
    reports_coll.update_one(
        {"_id": str(report_id)},
        {
            "$set": {
                "status": "completed",
                "pdfBytes": b64_pdf,
                "summaryJson": json.dumps(summary),
                "generatedAt": now,
                "updatedAt": now,
            }
        },
    )

    updated_report = reports_coll.find_one({"_id": str(report_id)})
    return updated_report
